### ISSUE TITLE
fix: cors 수정

### ISSUE THREAD

**Issue by Anhye0n** [tutorial-sejong/cr-backend#80]
## 📋 이슈 유형
- [X] 버그 수정 (Bug Report)
- [ ] 기능 개발 (Feature Request)
- [ ] 개선 사항 (Improvement)
- [ ] 기타 (Other)

## ✅ Todo
- [X] cors 경로 수정
- [X] 어드민 관련 설정 제거
